---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - as.agentstream.github.io
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - as.agentstream.github.io
  resources:
  - agents/finalizers
  verbs:
  - update
- apiGroups:
  - as.agentstream.github.io
  resources:
  - agents/status
  verbs:
  - get
  - patch
  - update
