apiVersion: as.agentstream.github.io/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-sample
spec:
  # TODO(user): Add fields here
